[package]
name = "didactic-enigma"
version = "0.1.0"
authors = ["Arth Tyagi <arthtyagi7@gmail.com>"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
requests = "0.0.30"
scraper = "0.11.0"
